%YAML 1.1
---
name: ai-router
version: 0.0.1
schema: v1

models:
  - name: router-auto
    provider: openai
    model: router-auto
    apiBase: http://localhost:8082/v1
    apiKey: ROUTER
    roles: [chat, autocomplete, edit, apply]

agent:
  chatModel: router-auto
  editModel: router-auto
  applyModel: router-auto
  autocompleteModel: router-auto
